### ISSUE TITLE
Implement Query Hint Support

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#344]
Implement query hint support for the Spanner Dialect.

`Dialect.setHint(String key, String value)`.

**Comment by elefeint** [comment]
I recall the last time we had issues supporting non-front-loaded hints. Would this still be a problem for, say, join hints?

**Comment by dzou** [comment]
There is some good news, looks like the hints are frontloaded now in the sql syntax!

https://cloud.google.com/spanner/docs/reference/standard-sql/query-syntax#sql_syntax

```
query_statement:
    [ statement_hint_expr ][ table_hint_expr ][ join_hint_expr ]
    query_expr

statement_hint_expr:
    '@{' statement_hint_key = statement_hint_value [, ...] '}'

statement_hint_key:
    {
      USE_ADDITIONAL_PARALLELISM
      | OPTIMIZER_VERSION
      | OPTIMIZER_STATISTICS_PACKAGE
      | ALLOW_DISTRIBUTED_MERGE
      | LOCK_SCANNED_RANGES
    }

query_expr:
    [ WITH cte[, ...] ]
    { select | ( query_expr ) | set_operation }
    [ ORDER BY expression [{ ASC | DESC }] [, ...] ]
    [ LIMIT count [ OFFSET skip_rows ] ]

```

**Comment by dzou** [comment]
@elefeint -- Actually I think I'm wrong about the prepended hints being supported... Despite the SQL syntax documentation, some query hints still must be applied to the part of the query.

I.e. `SELECT * FROM TABLE@{FORCE_INDEX=specify_table_idx_here}`.

I will do some research for how people solve this.

**Comment by rodrigogs** [comment]
So, there's no hint support?

No way I could do something like `@{FORCE_INDEX=my_index}` without using a native query?

**Comment by elefeint** [comment]
The short answer is no; there is no hint support.

The longer answer is that while implementing hints that precede the SQL query (statement hints) is reasonably easy, implementing Cloud Spanner join hints and table hints is infeasible without either Hibernate supporting a new hint type, or Spring Data JPA supporting Hibernate's custom database hint API. There is also a hackaround by using Hibernate comment hints, which we will not do because hackarounds are unmaintainable in the long term.

For complex queries, native queries are likely a more maintainable option even aside from needing hints.
