### ISSUE TITLE
Sequences exporter and dialect overrides

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#5]
This task involves checking the dialect functions related to sequences and implementing the exporter for sequences (that basically does nothing).

**Comment by ChengyuanZhao** [comment]
Functions including but not limited to: 

supportsSequences
supportsPooledSequences
getSequenceNextValString
getSelectSequenceNextValString
getCreateSequenceStrings
getCreateSequenceString
getDropSequenceStrings
getDropSequenceString
getQuerySequencesString
getSequenceInformationExtractor

**Comment by dzou** [comment]
Hi, I think no work needs to be done for this because Spanner does not support sequences, and the default Dialect methods [do not assume support for sequences](https://github.com/hibernate/hibernate-orm/blob/29e135c0150c4cbc7dd5ceea5986ddfcfa9a0354/hibernate-core/src/main/java/org/hibernate/dialect/Dialect.java#L796). I believe the default impls of all the methods are satisfactory.
