### ISSUE TITLE
Can you help improve hibernate-orm?

### ISSUE THREAD

**Issue by zdu-strong** [GoogleCloudPlatform/google-cloud-spanner-hibernate#577]
Hibernate-orm provides SpannerDialect, but not perfect.
DDL generation for unique constraints and foreign keys are both empty.
Can you help to perfect it?

File Location: [SpannerDialect File](https://github.com/hibernate/hibernate-orm/blob/cf42b134d251be5def379e7f557aafd4be7ba59e/hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java)

**Comment by olavloite** [comment]
@zdu-strong  We will first update this repository to also support Hibernate 6. Once that is done, we'll try to port at least some of those changes into the `SpannerDialect` in the Hibernate repository.

**Comment by zdu-strong** [comment]
Thanks for your effort. I'll keep looking forward to it.

**Comment by olavloite** [comment]
@zdu-strong Note that it is recommended to use this dialect to get the most feature-rich and up to date experience when using Hibernate with Spanner. This dialect also adds support for several Spanner-specific features that cannot be added to the SpannerDialect in the core repository. Is there a specific reason that you cannot use this dialect?

**Comment by zdu-strong** [comment]
> @zdu-strong Note that it is recommended to use this dialect to get the most feature-rich and up to date experience when using Hibernate with Spanner. This dialect also adds support for several Spanner-specific features that cannot be added to the SpannerDialect in the core repository. Is there a specific reason that you cannot use this dialect?

Thank you!
Good news! I tried upgrading the dependencies, then my program works fine.

**Comment by zdu-strong** [comment]
### 1. Unfortunately, the spanner dialect doesn't work properly (com.google.cloud.spanner.hibernate.SpannerDialect).

[https://github.com/zdu-strong/Temp_Bad_Work_Google_Spanner.git](https://github.com/zdu-strong/Temp_Bad_Work_Google_Spanner.git)
After completing the development environment setup, run command:
` ./mvn clean spring-boot:run`
Then you will see the error: 
![image](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/assets/48673442/805b93b5-66c1-438c-8a07-50662b04f70f)

Please restart the spanner emulator before each startup.

### 2. Works great with hibernate dialect (org.hibernate.dialect.SpannerDialect).

[https://github.com/zdu-strong/Temp_Good_Work_Hibernate_Spanner.git](https://github.com/zdu-strong/Temp_Good_Work_Hibernate_Spanner.git)
After completing the development environment setup, run command: 
` ./mvn clean spring-boot:run`
Then you will see the result: 
![image](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/assets/48673442/6a38a462-acfb-466c-80a1-be007e4fc235)

**Comment by olavloite** [comment]
Thanks for the extensive report and for sharing the code. I'll take a look.

**Comment by olavloite** [comment]
@zdu-strong The problem is caused by the combination of the following two things:

1. Your application extends the class `com.google.cloud.spanner.hibernate.SpannerDialect` class, and then uses this [custom dialect here](https://github.com/zdu-strong/Temp_Bad_Work_Google_Spanner/blob/b2096eee7a4b417b9c4eeba9cad78a0ba5aa2339/src/main/resources/application.yml#L10).
2. The `SpannerDialect` registers a custom `SchemaManagementTool` [here](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/3513f375a955bcf9eb86e076cea414cb0d4149f2/google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java#L52). However, it only does so if the dialect name is exactly equal to its own dialect name. That means that if you extend the `SpannerDialect`, then this registration does not happen.

So the solution here is:
1. For now, you could try to just use the `com.google.cloud.spanner.hibernate.SpannerDialect` directly. This works for me locally (although your application fails at startup for me due to some other non-Hibernate related error (`Field gitProperties in com.springboot.project.common.baseController.BaseController required a bean of type 'org.springframework.boot.info.GitProperties' that could not be found.`)
2. I will modify the code that registers the `SchemaManagementTool` so it also correctly handles any case where anyone has extended our Hibernate dialect to add additional features. That should enable the use of your custom dialect. (It'll probably be Monday before I get to that)

Regarding the additional functions that you are registering in your dialect: I'll add those to our dialect as well. Or if you want to, then feel free to open a pull request in this repository to add them :-)

**Comment by zdu-strong** [comment]
@olavloite Thank you very much for your help!
I've removed the GitProperties to make testing easier.

**Comment by zdu-strong** [comment]
It worked. Thank you so much.
