### ISSUE TITLE
Where to find google-cloud-spanner-hibernate-dialect: 3.0.0

### ISSUE THREAD

**Issue by credmond-git** [GoogleCloudPlatform/google-cloud-spanner-hibernate#820]
I am trying to include google-cloud-spanner-hibernate-dialect: 3.0.0 in my project but i am unable to find it. 
When looking at the maven repo the highest i see is 2.0 released Oct 25th. 
https://mvnrepository.com/artifact/com.google.cloud/google-cloud-spanner-hibernate-dialect

**Comment by burkedavison** [comment]
@olavloite : Staging build for 3.0.0 failed -- https://fusion2.corp.google.com/ci/kokoro/prod:cloud-java-frameworks%2Fgoogle-cloud-spanner-hibernate%2Fstage/activity/18651a0d-d7b0-4aba-bc37-84ff8c162d72/log

**Comment by olavloite** [comment]
@credmond-git Thanks for reaching out and sorry for the confusion. The initial push to Maven central failed due to the requirement to build with Java 17, and incompatibilities/bugs in one of the Maven plugins with Java 17. This has now been fixed and the newest version of the library (3.0.3) is now available in Maven central.
