### ISSUE TITLE
Non-functional/Unsupported features Exporters

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#9]
This involves providing implementations that generate BLANK statements for:

sequences
foreign key constraint
unique constraint
auxiliary constraint

**Comment by dzou** [comment]
From my research, I think the auxiliary exporter actually refers to the `AuxiliaryDatabaseObject` which can probably be supported in Spanner because it represents essentially a way for someone to run arbitrary SQL commands: https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/mapping-database-object.html
